# example netlify.toml
[build]
  command = "npm run build-netlify"
  functions = "functions-build" #  netlify-lambda reads this
  publish = "public"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200